# https://docs.frigate.video/configuration/reference/

version: 0.16-0

mqtt:
  host: mosquitto

tls:
  enabled: false

go2rtc:
  streams:
    cam1-main: onvif://{FRIGATE_TAPO_C200_USER}:{FRIGATE_TAPO_C200_PASSWORD}@tapo-c200:2020
    cam1-sub: onvif://{FRIGATE_TAPO_C200_USER}:{FRIGATE_TAPO_C200_PASSWORD}@tapo-c200:2020?subtype=1

birdseye:
  enabled: False

cameras:
  cam1: # Tapo C200
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1-sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam1-main
          roles:
            - record
            - audio
    objects:
      filters:
        person:
          min_score: 0.3
          threshold: 0.5

    onvif: # Only for PTZ
      host: tapo-c200
      port: 2020
      user: "{FRIGATE_TAPO_C200_USER}"
      password: "{FRIGATE_TAPO_C200_PASSWORD}"

audio:
  enabled: true

detect:
  enabled: true

record:
  enabled: true
  retain:
    days: 10
    mode: motion

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true

detectors:
  cpu1:
    type: openvino

model:
  width: 300
  height: 300
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

face_recognition:
  enabled: true
