http:
  middlewares:
    secure-headers:
      headers:
        contentTypeNosniff: true
        referrerPolicy: no-referrer
        permissionsPolicy: camera=(), microphone=(), geolocation=(), payment=()
    errp-redirect:
      errors:
        status: "400-599"
        service: errp@docker
        query: /{status}.html
    authelia:
      forwardAuth:
        address: 'http://authelia:9091/api/authz/forward-auth'
        trustForwardHeader: true
