# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !env_var LOCAL_IP

homeassistant:
  external_url: !env_var EXTERNAL_URL
  internal_url: !env_var EXTERNAL_URL

logger:
  logs:
    py.warnings: error

alarm_control_panel:
  - platform: manual
    arming_states:
      - armed_away
    code_arm_required: false
    arming_time: 0
    delay_time: 0

mqtt:
  sensor: !include mqtt_sensors.yaml
